FROM ubuntu:noble AS builder

RUN apt-get update && \
    apt-get install -y curl
COPY ./extract_deb.sh /extract_deb.sh
ARG TRUSTAGENT_VERSION
RUN /extract_deb.sh libssl11

FROM yusiwen/kasm-core-minimal:1.3.4-systemd
LABEL Author=yusiwen@gmail.com
LABEL Description="Qianxin(奇安信) TrustAgent VPN client within a minimal KASM core desktop" \
	License="GPLv2" \
	Version="3.4.1.1010.15"

USER root
RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y ca-certificates fonts-wqy-microhei libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-render-util0 libxcb-xinerama0 libxcb-xinput0 python3-xdg python-is-python3 psmisc zip net-tools iputils-ping dmidecode \
    && echo 'kasm-user ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers \
    && apt-get autoclean && rm -rf /var/lib/apt/list/*

COPY --from=builder /build/usr/ /usr/
COPY --from=builder /build/opt/ /opt/
COPY --from=builder /libssl11/usr/ /usr/

COPY ./systemd/trustdservice.service /usr/lib/systemd/system/trustdservice.service
COPY ./systemd/trustservice.service /usr/lib/systemd/system/trustservice.service
COPY ./systemd/trustservicemgr.service /usr/lib/systemd/system/trustservicemgr.service
COPY ./systemd/trustnet.service /usr/lib/systemd/system/trustnet.service
COPY ./install.sh /install.sh
COPY ./routes.sh /routes.sh

RUN /install.sh
RUN find /opt/apps/com.qianxin.trustagent/files -name '*.so*' -printf "%h\n" | sort | uniq > /etc/ld.so.conf.d/qianxin-trustagent.conf && \
    ldconfig && \
    sed -i -e 's/USE_INTERNAL_QT_FIRST=false/USE_INTERNAL_QT_FIRST=true/g' /opt/apps/com.qianxin.trustagent/files/bin/gui_opt.conf

ENV BYPASS_ROUTES=
ENV DNAT_RULES=

USER 1000

COPY ./defaults/menu.xml /home/kasm-user/.config/openbox/menu.xml
